title: Logo ERP Geliştirici Rehberi
description: Logo ERP (Tiger 3, Go3, Enterprise) veritabanı tabloları, SQL sorgu örnekleri ve geliştirici dokümantasyonu.
url: "https://sametzengins.github.io"
baseurl: "/Logo-ERP-Gelistirici-Rehberi"

# Remote theme kaldırıldı, özel tema kullanılıyor.
# remote_theme: ...

plugins:
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
permalink: /:title/
